### ISSUE TITLE
6 Snap Payment Methods

### ISSUE THREAD

**Issue by yofiesetiawan** [harrypujianto/SNAP-Opencart-2.3#1]
Pak Harry,

After we extract the file, we get these new payment methods
- Snap
- Snap bin filter
- Snap Installment
- Snap Installment Migs
- Snap Offline Installment
- Snap Migs

What are the difference? Can you add explaination about each of those? Should we install all or we can choose based on our preference? Maybe you can consider to add this information on readme file. Thanks!

**Comment by harrypujianto** [comment]
thank you for the input I'll add the details on readme.

snap: will show all payment methods enabled. creditcards, direct debit (mandiri clickpay, CIMB clicks, BCAKlikPay,BRI epay, klik BCA, and Emoneys)

Snap bin filter: creditcard only with whitelist bin feature, for promo..

Snap installment: CC installment only. with acquiring bank BNI Mandiri & CIMB

Snap Installment MIGS: CC installment only, with BCA, BRI & Maybank Acquiring

Snap Offline installment: CC installment only with other bank than mention above

Snap MIGS: CC Full payment only, with BCA / BRI/ Maybank Acquiring
